# fly.toml app configuration file generated for ama-browser on 2025-01-09T17:18:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ama-browser'
primary_region = 'fra'

[build]
dockerfile = '/config/docker/Dockerfile'

[http_service]
  internal_port = 5000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  script = "gunicorn -w 4 -b 0.0.0.0:5000 app:app"

[[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
source = "ama_browser"
destination = "/data"
